export const FETCH_NATURE_LIST='FETCH_NATURE_LIST'
export const FETCH_NATURE_DETAIL='FETCH_NATURE_DETAIL'
export const FETCH_NATURE_PAGE='FETCH_NATURE_PAGE'

export const FETCH_CULTURE_LIST='FETCH_CULTURE_LIST'
export const FETCH_CULTURE_DETAIL='FETCH_CULTURE_DETAIL'
export const FETCH_CULTURE_PAGE='FETCH_CULTURE_PAGE'

export const FETCH_HOTEL_LIST='FETCH_HOTEL_LIST'
export const FETCH_HOTEL_DETAIL='FETCH_HOTEL_DETAIL'
export const FETCH_HOTEL_PAGE='FETCH_HOTEL_PAGE'
export const FETCH_FIND_LIST='FETCH_FIND_LIST'
export const FETCH_FIND_PAGE='FETCH_FIND_PAGE'

// board
export const BOARD_LIST='BOARD_LIST'
export const BOARD_PAGE='BOARD_PAGE'
export const BOARD_DETAIL='BOARD_DETAIL'
export const BOARD_INSERT='BOARD_INSERT'
export const BOARD_UPDATE='BOARD_UPDATE'
export const BOARD_UPDATE_DATA='BOARD_UPDATE_DATA'
export const BOARD_DELETE='BOARD_DELETE'